# Generated by Django 5.1.5 on 2025-01-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='customer_id',
            field=models.CharField(default='UNKNOWN', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
