# Generated by Django 5.1.5 on 2025-01-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250120_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='customer_id',
        ),
    ]
