# Generated by Django 5.1.5 on 2025-01-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicerequest_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='attachment',
        ),
    ]
