# Generated by Django 5.1.5 on 2025-01-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicerequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
