# Generated by Django 5.1.5 on 2025-01-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicerequest_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
