# Generated by Django 5.1.5 on 2025-01-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicerequest_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='customer_id',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(max_length=100),
        ),
    ]
