# Generated by Django 5.1.5 on 2025-01-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_servicerequest_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('new_connection', 'New Connection'), ('modification', 'Service Modification'), ('maintenance', 'Maintenance and Repairs'), ('billing', 'Billing and Payment'), ('disconnection', 'Disconnection or Reconnection'), ('inspection', 'Safety Inspection'), ('upgrade', 'Service Upgrade'), ('emergency', 'Emergency Services'), ('general', 'General Inquiry')], max_length=50),
        ),
    ]
